name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6.3]
        gemfile:
          - rails_5.1_active_admin_1.0
          - rails_5.1_active_admin_1.2
          - rails_5.x_active_admin_1.3
          - rails_5.x_active_admin_2.x
        include:
          - ruby-version: 3.2
            gemfile: rails_6.1_active_admin_3.x
          - ruby-version: 3.2
            gemfile: rails_7.0_active_admin_3.x
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bin/rspec
